CREATE TABLE plantmonitor.temperature_measurement
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    comment text NOT NULL,
    device_id text NOT NULL,
    start_time timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS plantmonitor.temperature_measurement OWNER to postgres;

CREATE TABLE plantmonitor.temperature_measurement_value
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    temperature real NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    measurement_fk bigint NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (measurement_fk)
        REFERENCES plantmonitor.temperature_measurement (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);
ALTER TABLE IF EXISTS plantmonitor.temperature_measurement_value OWNER to postgres;

update plantmonitor.configuration_data set value='2' where key='PatchNumber';