CREATE TABLE plantmonitor.switchable_outlet_code
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_name text NOT NULL,
    code bigint NOT NULL,
    turns_on boolean NOT NULL,
    channel_number integer NOT NULL,
    channel_base_number integer NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS plantmonitor.switchable_outlet_code OWNER to postgres;

insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1397845,True,4,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1397844,False,4,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1397077,True,3,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1397076,False,3,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1394005,True,2,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1394004,False,2,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1381717,True,1,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',1381716,False,1,1);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4543573,True,4,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4543572,False,4,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4542805,True,3,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4542804,False,3,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4539733,True,2,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4539732,False,2,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4527445,True,1,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',4527444,False,1,2);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5330005,True,4,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5330004,False,4,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5329237,True,3,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5329236,False,3,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5326165,True,2,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5326164,False,2,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5313877,True,1,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5313876,False,1,3);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5526613,True,4,4);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5526612,False,4,4);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5525845,True,3,4);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5525844,False,3,4);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5522773,True,2,4);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5522772,False,2,4);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5510485,True,1,4);
insert into plantmonitor.switchable_outlet_code (description,outlet_name,code,turns_on,channel_number,channel_base_number) values ('Bestell-Nr.: 1208457 - WK, Hst.-Teile-Nr.: 1208457, EAN: 4016138910087','Renkforce Outlet',5510484,False,1,4);

update plantmonitor.configuration_data set value='3' where key='PatchNumber';