CREATE TABLE plantmonitor.device_switch_association
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    outlet_on_fk bigint NOT NULL,
    outlet_off_fk bigint NOT NULL,
    device_id uuid NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (outlet_on_fk)
        REFERENCES plantmonitor.switchable_outlet_code (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    FOREIGN KEY (outlet_off_fk)
        REFERENCES plantmonitor.switchable_outlet_code (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);
ALTER TABLE IF EXISTS plantmonitor.device_switch_association OWNER to postgres;

update plantmonitor.configuration_data set value='4' where key='PatchNumber';