CREATE TABLE plantmonitor.photo_tour_plant
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    comment text NOT NULL,
    qr_code text,
    photo_tour_fk bigint NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (photo_tour_fk)
        REFERENCES plantmonitor.automatic_photo_tour (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);
ALTER TABLE IF EXISTS plantmonitor.plant OWNER to postgres;

CREATE TABLE plantmonitor.plant_extraction_template
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    photo_trip_fk bigint NOT NULL,
    photo_tour_plant_fk bigint NOT NULL,
    photo_bounding_box polygon NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (photo_trip_fk)
        REFERENCES plantmonitor.photo_tour_trip (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    FOREIGN KEY (photo_tour_plant_fk)
        REFERENCES plantmonitor.photo_tour_plant (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);
ALTER TABLE IF EXISTS plantmonitor.photo_stitching_template ADD COLUMN motor_position integer NOT NULL;
ALTER TABLE IF EXISTS plantmonitor.photo_stitching_template OWNER to postgres;

ALTER TABLE IF EXISTS plantmonitor.photo_tour_trip ADD COLUMN virtual_picture_path text;

ALTER TABLE IF EXISTS plantmonitor.plant_extraction_template ADD COLUMN ir_bounding_box_offset point NOT NULL;

ALTER TABLE IF EXISTS plantmonitor.plant_extraction_template ADD COLUMN bounding_box_height real NOT NULL;
ALTER TABLE IF EXISTS plantmonitor.plant_extraction_template ADD COLUMN bounding_box_width real NOT NULL;

update plantmonitor.configuration_data set value='6' where key='PatchNumber';