CREATE TABLE plantmonitor.virtual_image_summary
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    virtual_image_path text NOT NULL,
    virtual_image_creation_date timestamp with time zone NOT NULL,
    data jsonb NOT NULL
);

ALTER TABLE IF EXISTS plantmonitor.virtual_image_summary OWNER to postgres;

update plantmonitor.configuration_data set value='8' where key='PatchNumber';